/*
 * RetroRacer - Embedded Vehicle Model Data
 * Auto-generated by tools/obj2c.sh - do not edit manually
 */

#ifndef MODEL_DATA_H
#define MODEL_DATA_H

#include "render.h"

/* Available vehicle models */
typedef enum {
    MODEL_CAR01,
    MODEL_CAR02,
    MODEL_CAR03,
    MODEL_POLICE,
    MODEL_PICKUP01,
    MODEL_PICKUP02,
    MODEL_BUS,
    MODEL_COUNT
} model_id_t;

/* Model metadata */
typedef struct {
    const char *name;
    int vertex_count;
    int face_count;
} model_info_t;

/* Get model info */
const model_info_t *model_get_info(model_id_t id);

/* Create a renderable mesh from model data with given color */
mesh_t *model_create_mesh(model_id_t id, uint32_t color);

#endif /* MODEL_DATA_H */
