/*
 * RetroRacer - Embedded Road Tile Data
 * Auto-generated by tools/tiles2c.sh - do not edit manually
 */

#ifndef TILE_DATA_H
#define TILE_DATA_H

#include "render.h"

/* Available road tile types */
typedef enum {
    TILE_STRAIGHT,
    TILE_CORNER,
    TILE_DAMAGED,
    TILE_SIDE,
    TILE_PAVEMENT,
    TILE_GRASS,
    TILE_COUNT
} tile_id_t;

/* Initialize shared tile meshes (call once at startup) */
void tile_init(void);

/* Free shared tile meshes (call at shutdown) */
void tile_shutdown(void);

/* Get the shared mesh for a tile type */
mesh_t *tile_get_mesh(tile_id_t id);

#endif /* TILE_DATA_H */
