#!/usr/bin/env python3
"""
OBJ to C converter for RetroRacer (Dreamcast)
Converts Wavefront OBJ files to C source/header with embedded mesh data.
Models are scaled and centered to fit the game's coordinate system.
"""

import os
import sys
import math

# Target vehicle dimensions (matching original mesh_create_vehicle)
TARGET_WIDTH = 1.6    # X extent
TARGET_HEIGHT = 0.8   # Y extent
TARGET_LENGTH = 3.0   # Z extent

# Models to convert: (id_name, obj_filename, display_name)
MODELS = [
    ("car01",    "car01.obj",    "Car 01"),
    ("car02",    "car02.obj",    "Car 02"),
    ("car03",    "car03.obj",    "Car 03"),
    ("police",   "police.obj",   "Police Car"),
    ("pickup01", "pickup01.obj", "Pickup Truck 01"),
    ("pickup02", "pickup02.obj", "Pickup Truck 02"),
    ("bus",      "bus.obj",      "Bus"),
]


def parse_obj(filepath):
    """Parse OBJ file, return vertices and triangle faces."""
    vertices = []
    faces = []

    with open(filepath, 'r') as f:
        for line in f:
            line = line.strip()
            if line.startswith('v '):
                parts = line.split()
                x, y, z = float(parts[1]), float(parts[2]), float(parts[3])
                vertices.append((x, y, z))
            elif line.startswith('f '):
                parts = line.split()[1:]
                # Parse face indices (OBJ is 1-indexed, may have v/vt/vn format)
                indices = []
                for p in parts:
                    idx = int(p.split('/')[0]) - 1  # Convert to 0-indexed
                    indices.append(idx)
                # Triangulate if needed (fan triangulation for convex faces)
                for i in range(1, len(indices) - 1):
                    faces.append((indices[0], indices[i], indices[i + 1]))

    return vertices, faces


def compute_bounds(vertices):
    """Compute bounding box of vertex list."""
    min_x = min(v[0] for v in vertices)
    max_x = max(v[0] for v in vertices)
    min_y = min(v[1] for v in vertices)
    max_y = max(v[1] for v in vertices)
    min_z = min(v[2] for v in vertices)
    max_z = max(v[2] for v in vertices)
    return (min_x, max_x, min_y, max_y, min_z, max_z)


def normalize_model(vertices):
    """Scale and center model to fit target dimensions. Y base stays at 0."""
    bounds = compute_bounds(vertices)
    min_x, max_x, min_y, max_y, min_z, max_z = bounds

    width = max_x - min_x
    height = max_y - min_y
    length = max_z - min_z

    # Find uniform scale to fit within target dimensions
    scale_x = TARGET_WIDTH / width if width > 0 else 1.0
    scale_y = TARGET_HEIGHT / height if height > 0 else 1.0
    scale_z = TARGET_LENGTH / length if length > 0 else 1.0
    scale = min(scale_x, scale_y, scale_z)

    # Center X and Z, keep Y base at 0
    center_x = (min_x + max_x) / 2.0
    center_z = (min_z + max_z) / 2.0

    result = []
    for x, y, z in vertices:
        nx = (x - center_x) * scale
        ny = (y - min_y) * scale  # Base at Y=0
        nz = (z - center_z) * scale
        result.append((nx, ny, nz))

    return result


def compute_face_normal(v0, v1, v2):
    """Compute face normal from 3 vertices."""
    # Edge vectors
    e1 = (v1[0] - v0[0], v1[1] - v0[1], v1[2] - v0[2])
    e2 = (v2[0] - v0[0], v2[1] - v0[1], v2[2] - v0[2])
    # Cross product
    nx = e1[1] * e2[2] - e1[2] * e2[1]
    ny = e1[2] * e2[0] - e1[0] * e2[2]
    nz = e1[0] * e2[1] - e1[1] * e2[0]
    # Normalize
    length = math.sqrt(nx * nx + ny * ny + nz * nz)
    if length > 0.0001:
        nx /= length
        ny /= length
        nz /= length
    return (nx, ny, nz)


def generate_header(models_info, out_path):
    """Generate model_data.h header file."""
    lines = []
    lines.append("/*")
    lines.append(" * RetroRacer - Embedded Vehicle Model Data")
    lines.append(" * Auto-generated by tools/obj2c.py - do not edit manually")
    lines.append(" */")
    lines.append("")
    lines.append("#ifndef MODEL_DATA_H")
    lines.append("#define MODEL_DATA_H")
    lines.append("")
    lines.append('#include "render.h"')
    lines.append("")
    lines.append("/* Available vehicle models */")
    lines.append("typedef enum {")
    for info in models_info:
        lines.append(f"    MODEL_{info['enum_name']},")
    lines.append("    MODEL_COUNT")
    lines.append("} model_id_t;")
    lines.append("")
    lines.append("/* Model metadata */")
    lines.append("typedef struct {")
    lines.append("    const char *name;")
    lines.append("    int vertex_count;")
    lines.append("    int face_count;")
    lines.append("} model_info_t;")
    lines.append("")
    lines.append("/* Get model info */")
    lines.append("const model_info_t *model_get_info(model_id_t id);")
    lines.append("")
    lines.append("/* Create a renderable mesh from model data with given color */")
    lines.append("mesh_t *model_create_mesh(model_id_t id, uint32_t color);")
    lines.append("")
    lines.append("#endif /* MODEL_DATA_H */")
    lines.append("")

    with open(out_path, 'w') as f:
        f.write('\n'.join(lines))
    print(f"  Generated {out_path}")


def generate_source(models_data, out_path):
    """Generate model_data.c source file with embedded vertex/face arrays."""
    lines = []
    lines.append("/*")
    lines.append(" * RetroRacer - Embedded Vehicle Model Data")
    lines.append(" * Auto-generated by tools/obj2c.py - do not edit manually")
    lines.append(" *")
    lines.append(" * Models from Devil's Work.shop Low Poly Cars pack")
    lines.append(" * https://devilsworkshop.itch.io/")
    lines.append(" */")
    lines.append("")
    lines.append('#include "model_data.h"')
    lines.append("#include <stdlib.h>")
    lines.append("#include <string.h>")
    lines.append("")

    # Emit static vertex and face arrays for each model
    for m in models_data:
        name = m['id_name']
        verts = m['vertices']
        faces = m['faces']

        # Vertex positions
        lines.append(f"/* {m['display_name']}: {len(verts)} vertices, {len(faces)} triangles */")
        lines.append(f"static const float {name}_verts[] = {{")
        for i, (x, y, z) in enumerate(verts):
            comma = "," if i < len(verts) - 1 else ""
            lines.append(f"    {x:10.6f}f, {y:10.6f}f, {z:10.6f}f{comma}")
        lines.append("};")
        lines.append("")

        # Face indices (3 ints per triangle)
        lines.append(f"static const int {name}_faces[] = {{")
        for i, (a, b, c) in enumerate(faces):
            comma = "," if i < len(faces) - 1 else ""
            lines.append(f"    {a}, {b}, {c}{comma}")
        lines.append("};")
        lines.append("")

        # Face normals (for shading)
        lines.append(f"static const float {name}_normals[] = {{")
        for i, (a, b, c) in enumerate(faces):
            normal = compute_face_normal(verts[a], verts[b], verts[c])
            comma = "," if i < len(faces) - 1 else ""
            lines.append(f"    {normal[0]:8.5f}f, {normal[1]:8.5f}f, {normal[2]:8.5f}f{comma}")
        lines.append("};")
        lines.append("")

    # Model info table
    lines.append("/* Model info table */")
    lines.append("static const model_info_t model_info_table[] = {")
    for m in models_data:
        lines.append(f'    {{"{m["display_name"]}", {len(m["vertices"])}, {len(m["faces"])}}},')
    lines.append("};")
    lines.append("")

    # model_get_info
    lines.append("const model_info_t *model_get_info(model_id_t id) {")
    lines.append("    if (id < 0 || id >= MODEL_COUNT) return &model_info_table[0];")
    lines.append("    return &model_info_table[id];")
    lines.append("}")
    lines.append("")

    # Helper to shade a base color by face normal (basic directional lighting)
    lines.append("/* Apply basic directional shading to a base color */")
    lines.append("static uint32_t shade_color(uint32_t base, float nx, float ny, float nz) {")
    lines.append("    /* Light direction: slightly from above-right-front */")
    lines.append("    float lx = 0.3f, ly = 0.7f, lz = 0.5f;")
    lines.append("    float len = lx*lx + ly*ly + lz*lz;")
    lines.append("    if (len > 0) { len = 1.0f / len; }  /* Approx normalize */")
    lines.append("    float dot = (nx * lx + ny * ly + nz * lz);")
    lines.append("    if (dot < 0) dot = 0;")
    lines.append("    /* Ambient 0.4 + diffuse 0.6 */")
    lines.append("    float intensity = 0.4f + 0.6f * dot;")
    lines.append("    if (intensity > 1.0f) intensity = 1.0f;")
    lines.append("")
    lines.append("    uint32_t a = (base >> 24) & 0xFF;")
    lines.append("    uint32_t r = (uint32_t)(((base >> 16) & 0xFF) * intensity);")
    lines.append("    uint32_t g = (uint32_t)(((base >> 8) & 0xFF) * intensity);")
    lines.append("    uint32_t b = (uint32_t)((base & 0xFF) * intensity);")
    lines.append("    return (a << 24) | (r << 16) | (g << 8) | b;")
    lines.append("}")
    lines.append("")

    # model_create_mesh - the main function
    lines.append("mesh_t *model_create_mesh(model_id_t id, uint32_t color) {")
    lines.append("    const float *verts;")
    lines.append("    const int *faces;")
    lines.append("    const float *normals;")
    lines.append("    int vert_count, face_count;")
    lines.append("")
    lines.append("    switch (id) {")
    for m in models_data:
        name = m['id_name']
        enum = m['enum_name']
        lines.append(f"        case MODEL_{enum}:")
        lines.append(f"            verts = {name}_verts;")
        lines.append(f"            faces = {name}_faces;")
        lines.append(f"            normals = {name}_normals;")
        lines.append(f"            vert_count = {len(m['vertices'])};")
        lines.append(f"            face_count = {len(m['faces'])};")
        lines.append(f"            break;")
    lines.append("        default:")
    lines.append(f"            verts = {models_data[0]['id_name']}_verts;")
    lines.append(f"            faces = {models_data[0]['id_name']}_faces;")
    lines.append(f"            normals = {models_data[0]['id_name']}_normals;")
    lines.append(f"            vert_count = {len(models_data[0]['vertices'])};")
    lines.append(f"            face_count = {len(models_data[0]['faces'])};")
    lines.append("            break;")
    lines.append("    }")
    lines.append("")
    lines.append("    (void)vert_count;")
    lines.append("")
    lines.append("    mesh_t *mesh = (mesh_t *)malloc(sizeof(mesh_t));")
    lines.append("    if (!mesh) return NULL;")
    lines.append("")
    lines.append("    mesh->tri_count = face_count;")
    lines.append("    mesh->triangles = (triangle_t *)malloc(sizeof(triangle_t) * face_count);")
    lines.append("    if (!mesh->triangles) { free(mesh); return NULL; }")
    lines.append("    mesh->base_color = color;")
    lines.append("")
    lines.append("    for (int i = 0; i < face_count; i++) {")
    lines.append("        int i0 = faces[i * 3 + 0];")
    lines.append("        int i1 = faces[i * 3 + 1];")
    lines.append("        int i2 = faces[i * 3 + 2];")
    lines.append("")
    lines.append("        /* Shade color based on face normal */")
    lines.append("        float nx = normals[i * 3 + 0];")
    lines.append("        float ny = normals[i * 3 + 1];")
    lines.append("        float nz = normals[i * 3 + 2];")
    lines.append("        uint32_t shaded = shade_color(color, nx, ny, nz);")
    lines.append("")
    lines.append("        mesh->triangles[i].v[0].pos.x = verts[i0 * 3 + 0];")
    lines.append("        mesh->triangles[i].v[0].pos.y = verts[i0 * 3 + 1];")
    lines.append("        mesh->triangles[i].v[0].pos.z = verts[i0 * 3 + 2];")
    lines.append("        mesh->triangles[i].v[0].color = shaded;")
    lines.append("")
    lines.append("        mesh->triangles[i].v[1].pos.x = verts[i1 * 3 + 0];")
    lines.append("        mesh->triangles[i].v[1].pos.y = verts[i1 * 3 + 1];")
    lines.append("        mesh->triangles[i].v[1].pos.z = verts[i1 * 3 + 2];")
    lines.append("        mesh->triangles[i].v[1].color = shaded;")
    lines.append("")
    lines.append("        mesh->triangles[i].v[2].pos.x = verts[i2 * 3 + 0];")
    lines.append("        mesh->triangles[i].v[2].pos.y = verts[i2 * 3 + 1];")
    lines.append("        mesh->triangles[i].v[2].pos.z = verts[i2 * 3 + 2];")
    lines.append("        mesh->triangles[i].v[2].color = shaded;")
    lines.append("    }")
    lines.append("")
    lines.append("    return mesh;")
    lines.append("}")
    lines.append("")

    with open(out_path, 'w') as f:
        f.write('\n'.join(lines))
    print(f"  Generated {out_path}")


def main():
    # Determine paths
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)
    obj_dir = os.path.join(project_root, "assets", "models", "obj")
    header_path = os.path.join(project_root, "include", "model_data.h")
    source_path = os.path.join(project_root, "src", "model_data.c")

    print("RetroRacer OBJ-to-C Converter")
    print(f"  Source: {obj_dir}")
    print(f"  Output: {header_path}")
    print(f"          {source_path}")
    print()

    models_data = []
    models_info = []

    for id_name, obj_file, display_name in MODELS:
        obj_path = os.path.join(obj_dir, obj_file)
        if not os.path.exists(obj_path):
            print(f"  WARNING: {obj_path} not found, skipping")
            continue

        print(f"  Processing {obj_file}...")
        vertices, faces = parse_obj(obj_path)
        bounds = compute_bounds(vertices)
        print(f"    Raw: {len(vertices)} verts, {len(faces)} tris")
        print(f"    Bounds: X[{bounds[0]:.1f}, {bounds[1]:.1f}] "
              f"Y[{bounds[2]:.1f}, {bounds[3]:.1f}] "
              f"Z[{bounds[4]:.1f}, {bounds[5]:.1f}]")

        # Normalize to game scale
        vertices = normalize_model(vertices)
        nbounds = compute_bounds(vertices)
        print(f"    Scaled: X[{nbounds[0]:.3f}, {nbounds[1]:.3f}] "
              f"Y[{nbounds[2]:.3f}, {nbounds[3]:.3f}] "
              f"Z[{nbounds[4]:.3f}, {nbounds[5]:.3f}]")

        enum_name = id_name.upper()
        models_data.append({
            'id_name': id_name,
            'enum_name': enum_name,
            'display_name': display_name,
            'vertices': vertices,
            'faces': faces,
        })
        models_info.append({
            'enum_name': enum_name,
        })

    if not models_data:
        print("ERROR: No models found!")
        sys.exit(1)

    print()
    generate_header(models_info, header_path)
    generate_source(models_data, source_path)

    # Print summary
    total_verts = sum(len(m['vertices']) for m in models_data)
    total_faces = sum(len(m['faces']) for m in models_data)
    # Estimate: 3 floats per vert + 3 ints per face + 3 floats per face normal
    est_bytes = total_verts * 12 + total_faces * 12 + total_faces * 12
    print(f"\n  Total: {len(models_data)} models, {total_verts} vertices, {total_faces} triangles")
    print(f"  Estimated static data: ~{est_bytes // 1024} KB")
    print("  Done!")


if __name__ == "__main__":
    main()
