#!/bin/bash
# OBJ to C converter for RetroRacer (Dreamcast)
# Uses awk to parse OBJ files and generate C source with embedded mesh data.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
OBJ_DIR="$PROJECT_ROOT/assets/models/obj"
HEADER="$PROJECT_ROOT/include/model_data.h"
SOURCE="$PROJECT_ROOT/src/model_data.c"

# Target dimensions for scaling
TARGET_W=1.6
TARGET_H=0.8
TARGET_L=3.0

echo "RetroRacer OBJ-to-C Converter (awk)"

# Model definitions: enum_name:filename:display_name
MODELS=(
    "CAR01:car01.obj:Car 01"
    "CAR02:car02.obj:Car 02"
    "CAR03:car03.obj:Car 03"
    "POLICE:police.obj:Police Car"
    "PICKUP01:pickup01.obj:Pickup Truck 01"
    "PICKUP02:pickup02.obj:Pickup Truck 02"
    "BUS:bus.obj:Bus"
)

# Generate a single model's C arrays using awk
generate_model() {
    local enum_name="$1"
    local obj_file="$2"
    local display_name="$3"
    local var_name=$(echo "$enum_name" | tr '[:upper:]' '[:lower:]')

    awk -v target_w="$TARGET_W" -v target_h="$TARGET_H" -v target_l="$TARGET_L" \
        -v var_name="$var_name" -v display_name="$display_name" '
    BEGIN {
        vc = 0; fc = 0;
        minx = 999999; maxx = -999999;
        miny = 999999; maxy = -999999;
        minz = 999999; maxz = -999999;
    }
    /^v / {
        vc++;
        vx[vc] = $2; vy[vc] = $3; vz[vc] = $4;
        if ($2 < minx) minx = $2;
        if ($2 > maxx) maxx = $2;
        if ($3 < miny) miny = $3;
        if ($3 > maxy) maxy = $3;
        if ($4 < minz) minz = $4;
        if ($4 > maxz) maxz = $4;
    }
    /^f / {
        fc++;
        # Parse v/vt/vn format
        split($2, a, "/"); fi0[fc] = a[1];
        split($3, b, "/"); fi1[fc] = b[1];
        split($4, c, "/"); fi2[fc] = c[1];
    }
    END {
        # Compute scale
        width = maxx - minx;
        height = maxy - miny;
        depth = maxz - minz;
        sx = (width > 0) ? target_w / width : 1;
        sy = (height > 0) ? target_h / height : 1;
        sz = (depth > 0) ? target_l / depth : 1;
        # Uniform scale
        scale = sx;
        if (sy < scale) scale = sy;
        if (sz < scale) scale = sz;
        cx = (minx + maxx) / 2.0;
        cz = (minz + maxz) / 2.0;

        # Scale vertices
        for (i = 1; i <= vc; i++) {
            vx[i] = (vx[i] - cx) * scale;
            vy[i] = (vy[i] - miny) * scale;
            vz[i] = (vz[i] - cz) * scale;
        }

        printf "/* %s: %d vertices, %d triangles */\n", display_name, vc, fc;

        # Vertex array
        printf "static const float %s_verts[] = {\n", var_name;
        for (i = 1; i <= vc; i++) {
            comma = (i < vc) ? "," : "";
            printf "    %10.6ff, %10.6ff, %10.6ff%s\n", vx[i], vy[i], vz[i], comma;
        }
        printf "};\n\n";

        # Face index array
        printf "static const int %s_faces[] = {\n", var_name;
        for (i = 1; i <= fc; i++) {
            comma = (i < fc) ? "," : "";
            # Convert to 0-indexed
            printf "    %d, %d, %d%s\n", fi0[i]-1, fi1[i]-1, fi2[i]-1, comma;
        }
        printf "};\n\n";

        # Face normals
        printf "static const float %s_normals[] = {\n", var_name;
        for (i = 1; i <= fc; i++) {
            fa = fi0[i]; fb = fi1[i]; fcc = fi2[i];
            # Edge vectors
            e1x = vx[fb] - vx[fa]; e1y = vy[fb] - vy[fa]; e1z = vz[fb] - vz[fa];
            e2x = vx[fcc] - vx[fa]; e2y = vy[fcc] - vy[fa]; e2z = vz[fcc] - vz[fa];
            # Cross product
            nx = e1y * e2z - e1z * e2y;
            ny = e1z * e2x - e1x * e2z;
            nz = e1x * e2y - e1y * e2x;
            # Normalize
            len = sqrt(nx*nx + ny*ny + nz*nz);
            if (len > 0.0001) { nx /= len; ny /= len; nz /= len; }
            comma = (i < fc) ? "," : "";
            printf "    %8.5ff, %8.5ff, %8.5ff%s\n", nx, ny, nz, comma;
        }
        printf "};\n\n";

        # Output metadata for later use
        printf "/* META: %s %d %d */\n\n", var_name, vc, fc;
    }
    ' "$OBJ_DIR/$obj_file"
}

# ----- Generate Header -----
cat > "$HEADER" << 'HEADER_EOF'
/*
 * RetroRacer - Embedded Vehicle Model Data
 * Auto-generated by tools/obj2c.sh - do not edit manually
 */

#ifndef MODEL_DATA_H
#define MODEL_DATA_H

#include "render.h"

/* Available vehicle models */
typedef enum {
HEADER_EOF

for entry in "${MODELS[@]}"; do
    IFS=':' read -r enum_name obj_file display_name <<< "$entry"
    echo "    MODEL_${enum_name}," >> "$HEADER"
done

cat >> "$HEADER" << 'HEADER_EOF'
    MODEL_COUNT
} model_id_t;

/* Model metadata */
typedef struct {
    const char *name;
    int vertex_count;
    int face_count;
} model_info_t;

/* Get model info */
const model_info_t *model_get_info(model_id_t id);

/* Create a renderable mesh from model data with given color */
mesh_t *model_create_mesh(model_id_t id, uint32_t color);

#endif /* MODEL_DATA_H */
HEADER_EOF

echo "  Generated $HEADER"

# ----- Generate Source -----
cat > "$SOURCE" << 'SOURCE_HEADER'
/*
 * RetroRacer - Embedded Vehicle Model Data
 * Auto-generated by tools/obj2c.sh - do not edit manually
 *
 * Models from Devil's Work.shop Low Poly Cars pack
 * https://devilsworkshop.itch.io/
 */

#include "model_data.h"
#include <stdlib.h>
#include <string.h>
#include <math.h>

SOURCE_HEADER

# Generate each model's data
for entry in "${MODELS[@]}"; do
    IFS=':' read -r enum_name obj_file display_name <<< "$entry"
    echo "  Processing $obj_file..."
    generate_model "$enum_name" "$obj_file" "$display_name" >> "$SOURCE"
done

# Generate the info table
echo "/* Model info table */" >> "$SOURCE"
echo "static const model_info_t model_info_table[] = {" >> "$SOURCE"
for entry in "${MODELS[@]}"; do
    IFS=':' read -r enum_name obj_file display_name <<< "$entry"
    var_name=$(echo "$enum_name" | tr '[:upper:]' '[:lower:]')
    # Extract vertex/face counts from the META comment
    vc=$(grep -c "^v " "$OBJ_DIR/$obj_file")
    fc=$(grep -c "^f " "$OBJ_DIR/$obj_file")
    echo "    {\"$display_name\", $vc, $fc}," >> "$SOURCE"
done
echo "};" >> "$SOURCE"
echo "" >> "$SOURCE"

# Generate the rest of the functions
cat >> "$SOURCE" << 'FUNCS'
const model_info_t *model_get_info(model_id_t id) {
    if (id < 0 || id >= MODEL_COUNT) return &model_info_table[0];
    return &model_info_table[id];
}

/* Apply basic directional shading to a base color */
static uint32_t shade_color(uint32_t base, float nx, float ny, float nz) {
    /* Light direction: slightly from above-right-front */
    float dot = nx * 0.3f + ny * 0.7f + nz * 0.5f;
    if (dot < 0) dot = 0;
    /* Ambient 0.4 + diffuse 0.6 */
    float intensity = 0.4f + 0.6f * dot;
    if (intensity > 1.0f) intensity = 1.0f;

    uint32_t a = (base >> 24) & 0xFF;
    uint32_t r = (uint32_t)(((base >> 16) & 0xFF) * intensity);
    uint32_t g = (uint32_t)(((base >> 8) & 0xFF) * intensity);
    uint32_t b = (uint32_t)((base & 0xFF) * intensity);
    return (a << 24) | (r << 16) | (g << 8) | b;
}

FUNCS

# Generate the switch-based model_create_mesh function
echo "mesh_t *model_create_mesh(model_id_t id, uint32_t color) {" >> "$SOURCE"
echo "    const float *verts;" >> "$SOURCE"
echo "    const int *faces;" >> "$SOURCE"
echo "    const float *normals;" >> "$SOURCE"
echo "    int vert_count, face_count;" >> "$SOURCE"
echo "" >> "$SOURCE"
echo "    switch (id) {" >> "$SOURCE"

FIRST_VAR=""
FIRST_VC=""
FIRST_FC=""
for entry in "${MODELS[@]}"; do
    IFS=':' read -r enum_name obj_file display_name <<< "$entry"
    var_name=$(echo "$enum_name" | tr '[:upper:]' '[:lower:]')
    vc=$(grep -c "^v " "$OBJ_DIR/$obj_file")
    fc=$(grep -c "^f " "$OBJ_DIR/$obj_file")
    if [ -z "$FIRST_VAR" ]; then
        FIRST_VAR="$var_name"
        FIRST_VC="$vc"
        FIRST_FC="$fc"
    fi
    echo "        case MODEL_${enum_name}:" >> "$SOURCE"
    echo "            verts = ${var_name}_verts;" >> "$SOURCE"
    echo "            faces = ${var_name}_faces;" >> "$SOURCE"
    echo "            normals = ${var_name}_normals;" >> "$SOURCE"
    echo "            vert_count = ${vc};" >> "$SOURCE"
    echo "            face_count = ${fc};" >> "$SOURCE"
    echo "            break;" >> "$SOURCE"
done

echo "        default:" >> "$SOURCE"
echo "            verts = ${FIRST_VAR}_verts;" >> "$SOURCE"
echo "            faces = ${FIRST_VAR}_faces;" >> "$SOURCE"
echo "            normals = ${FIRST_VAR}_normals;" >> "$SOURCE"
echo "            vert_count = ${FIRST_VC};" >> "$SOURCE"
echo "            face_count = ${FIRST_FC};" >> "$SOURCE"
echo "            break;" >> "$SOURCE"
echo "    }" >> "$SOURCE"

cat >> "$SOURCE" << 'CREATE_MESH'

    (void)vert_count;

    mesh_t *mesh = (mesh_t *)malloc(sizeof(mesh_t));
    if (!mesh) return NULL;

    mesh->tri_count = face_count;
    mesh->triangles = (triangle_t *)malloc(sizeof(triangle_t) * face_count);
    if (!mesh->triangles) { free(mesh); return NULL; }
    mesh->base_color = color;

    for (int i = 0; i < face_count; i++) {
        int i0 = faces[i * 3 + 0];
        int i1 = faces[i * 3 + 1];
        int i2 = faces[i * 3 + 2];

        /* Shade color based on face normal */
        float nx = normals[i * 3 + 0];
        float ny = normals[i * 3 + 1];
        float nz = normals[i * 3 + 2];
        uint32_t shaded = shade_color(color, nx, ny, nz);

        mesh->triangles[i].v[0].pos.x = verts[i0 * 3 + 0];
        mesh->triangles[i].v[0].pos.y = verts[i0 * 3 + 1];
        mesh->triangles[i].v[0].pos.z = verts[i0 * 3 + 2];
        mesh->triangles[i].v[0].color = shaded;

        mesh->triangles[i].v[1].pos.x = verts[i1 * 3 + 0];
        mesh->triangles[i].v[1].pos.y = verts[i1 * 3 + 1];
        mesh->triangles[i].v[1].pos.z = verts[i1 * 3 + 2];
        mesh->triangles[i].v[1].color = shaded;

        mesh->triangles[i].v[2].pos.x = verts[i2 * 3 + 0];
        mesh->triangles[i].v[2].pos.y = verts[i2 * 3 + 1];
        mesh->triangles[i].v[2].pos.z = verts[i2 * 3 + 2];
        mesh->triangles[i].v[2].color = shaded;
    }

    return mesh;
}
CREATE_MESH

echo "  Generated $SOURCE"
echo "  Done!"
