/*
 * RetroRacer - Embedded Road Tile Data
 * Auto-generated by tools/tiles2c.sh - do not edit manually
 *
 * Road tile models from Kenney Retro Urban Kit
 * https://kenney.nl/
 */

#include "tile_data.h"
#include <stdlib.h>
#include <string.h>
#include <math.h>

/* Road Straight: 16 vertices, 22 triangles */
static const float straight_verts[] = {
     -6.000000f,   0.000000f,  -6.000000f,
     -6.000000f,   0.050000f,  -6.000000f,
    -12.000000f,   0.000000f,  -6.000000f,
    -12.000000f,   0.050000f,  -6.000000f,
     -6.000000f,   0.050000f,   6.000000f,
    -12.000000f,   0.050000f,   6.000000f,
     -6.000000f,   0.000000f,   6.000000f,
    -12.000000f,   0.000000f,   6.000000f,
     12.000000f,   0.000000f,  -6.000000f,
     12.000000f,   0.000000f,   6.000000f,
     12.000000f,   0.050000f,  -6.000000f,
     12.000000f,   0.050000f,   6.000000f,
      6.000000f,   0.050000f,   6.000000f,
      6.000000f,   0.000000f,   6.000000f,
      6.000000f,   0.000000f,  -6.000000f,
      6.000000f,   0.050000f,  -6.000000f
};

static const int straight_faces[] = {
    2, 1, 0,
    1, 2, 3,
    1, 5, 4,
    5, 1, 3,
    5, 6, 4,
    6, 5, 7,
    1, 6, 0,
    6, 1, 4,
    5, 2, 7,
    2, 5, 3,
    10, 9, 8,
    9, 10, 11,
    12, 9, 11,
    9, 12, 13,
    12, 14, 13,
    14, 12, 15,
    11, 15, 12,
    15, 11, 10,
    14, 10, 8,
    10, 14, 15,
    13, 0, 6,
    0, 13, 14
};

static const float straight_normals[] = {
     0.00000f,  0.00000f, -1.00000f,
    -0.00000f,  0.00000f, -1.00000f,
     0.00000f,  1.00000f, -0.00000f,
     0.00000f,  1.00000f,  0.00000f,
    -0.00000f,  0.00000f,  1.00000f,
     0.00000f,  0.00000f,  1.00000f,
     1.00000f,  0.00000f,  0.00000f,
     1.00000f, -0.00000f,  0.00000f,
    -1.00000f, -0.00000f,  0.00000f,
    -1.00000f,  0.00000f,  0.00000f,
     1.00000f,  0.00000f,  0.00000f,
     1.00000f, -0.00000f,  0.00000f,
    -0.00000f,  0.00000f,  1.00000f,
     0.00000f,  0.00000f,  1.00000f,
    -1.00000f, -0.00000f,  0.00000f,
    -1.00000f,  0.00000f,  0.00000f,
     0.00000f,  1.00000f,  0.00000f,
     0.00000f,  1.00000f,  0.00000f,
     0.00000f,  0.00000f, -1.00000f,
    -0.00000f,  0.00000f, -1.00000f,
     0.00000f,  1.00000f,  0.00000f,
     0.00000f,  1.00000f,  0.00000f
};

static const unsigned int straight_colors[] = {
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF404040,
    0xFF404040
};

/* Road Corner: 30 vertices, 50 triangles */
static const float corner_verts[] = {
     -6.000000f,   0.000000f,  12.000000f,
     -6.803848f,   0.000000f,   9.000000f,
      6.000000f,   0.000000f,  12.000000f,
      5.386664f,   0.000000f,   7.341257f,
     -9.000000f,   0.000000f,   6.803848f,
      3.588457f,   0.000000f,   3.000000f,
    -12.000000f,   0.000000f,   6.000000f,
    -12.000000f,   0.000000f,  -6.000000f,
      0.727922f,   0.000000f,  -0.727922f,
     -3.000000f,   0.000000f,  -3.588457f,
     -7.341257f,   0.000000f,  -5.386664f,
     12.000000f,   0.000000f, -12.000000f,
     12.000000f,   0.000000f,  12.000000f,
     12.000000f,   0.050000f, -12.000000f,
     12.000000f,   0.050000f,  12.000000f,
      6.000000f,   0.050000f,  12.000000f,
      5.386664f,   0.050000f,   7.341257f,
      3.588457f,   0.050000f,   3.000000f,
      0.727922f,   0.050000f,  -0.727922f,
     -3.000000f,   0.050000f,  -3.588457f,
     -7.341257f,   0.050000f,  -5.386664f,
    -12.000000f,   0.050000f,  -6.000000f,
    -12.000000f,   0.050000f, -12.000000f,
    -12.000000f,   0.000000f, -12.000000f,
     -6.000000f,   0.050000f,  12.000000f,
    -12.000000f,   0.050000f,  12.000000f,
     -6.803848f,   0.050000f,   9.000000f,
    -12.000000f,   0.050000f,   6.000000f,
     -9.000000f,   0.050000f,   6.803848f,
    -12.000000f,   0.000000f,  12.000000f
};

static const int corner_faces[] = {
    2, 1, 0,
    1, 2, 3,
    1, 3, 4,
    4, 3, 5,
    4, 5, 6,
    6, 5, 7,
    7, 5, 8,
    7, 8, 9,
    7, 9, 10,
    13, 12, 11,
    12, 13, 14,
    15, 12, 14,
    12, 15, 2,
    13, 15, 14,
    15, 13, 16,
    16, 13, 17,
    17, 13, 18,
    18, 13, 19,
    19, 13, 20,
    20, 13, 21,
    21, 13, 22,
    23, 13, 11,
    13, 23, 22,
    16, 2, 15,
    2, 16, 3,
    17, 3, 16,
    3, 17, 5,
    18, 5, 17,
    5, 18, 8,
    19, 8, 18,
    8, 19, 9,
    20, 9, 19,
    9, 20, 10,
    21, 10, 20,
    10, 21, 7,
    21, 23, 7,
    23, 21, 22,
    26, 25, 24,
    25, 26, 27,
    27, 26, 28,
    25, 6, 29,
    6, 25, 27,
    25, 0, 24,
    0, 25, 29,
    0, 26, 24,
    26, 0, 1,
    4, 26, 1,
    26, 4, 28,
    6, 28, 4,
    28, 6, 27
};

static const float corner_normals[] = {
    -0.00000f,  1.00000f,  0.00000f,
    -0.00000f,  1.00000f,  0.00000f,
    -0.00000f,  1.00000f,  0.00000f,
    -0.00000f,  1.00000f,  0.00000f,
    -0.00000f,  1.00000f,  0.00000f,
    -0.00000f,  1.00000f, -0.00000f,
    -0.00000f,  1.00000f, -0.00000f,
    -0.00000f,  1.00000f,  0.00000f,
    -0.00000f,  1.00000f, -0.00000f,
     1.00000f,  0.00000f,  0.00000f,
     1.00000f, -0.00000f,  0.00000f,
    -0.00000f,  0.00000f,  1.00000f,
     0.00000f,  0.00000f,  1.00000f,
     0.00000f,  1.00000f, -0.00000f,
     0.00000f,  1.00000f,  0.00000f,
     0.00000f,  1.00000f,  0.00000f,
     0.00000f,  1.00000f,  0.00000f,
     0.00000f,  1.00000f,  0.00000f,
     0.00000f,  1.00000f,  0.00000f,
     0.00000f,  1.00000f,  0.00000f,
     0.00000f,  1.00000f,  0.00000f,
     0.00000f,  0.00000f, -1.00000f,
    -0.00000f,  0.00000f, -1.00000f,
    -0.99144f,  0.00000f,  0.13053f,
    -0.99144f,  0.00000f,  0.13053f,
    -0.92388f,  0.00000f,  0.38268f,
    -0.92388f,  0.00000f,  0.38268f,
    -0.79335f,  0.00000f,  0.60876f,
    -0.79335f,  0.00000f,  0.60876f,
    -0.60876f,  0.00000f,  0.79335f,
    -0.60876f,  0.00000f,  0.79335f,
    -0.38268f,  0.00000f,  0.92388f,
    -0.38268f,  0.00000f,  0.92388f,
    -0.13053f,  0.00000f,  0.99144f,
    -0.13053f,  0.00000f,  0.99144f,
    -1.00000f, -0.00000f,  0.00000f,
    -1.00000f,  0.00000f,  0.00000f,
     0.00000f,  1.00000f, -0.00000f,
     0.00000f,  1.00000f,  0.00000f,
     0.00000f,  1.00000f,  0.00000f,
    -1.00000f, -0.00000f,  0.00000f,
    -1.00000f,  0.00000f,  0.00000f,
    -0.00000f,  0.00000f,  1.00000f,
     0.00000f,  0.00000f,  1.00000f,
     0.96593f,  0.00000f, -0.25882f,
     0.96593f,  0.00000f, -0.25882f,
     0.70711f,  0.00000f, -0.70711f,
     0.70711f,  0.00000f, -0.70711f,
     0.25882f,  0.00000f, -0.96593f,
     0.25882f,  0.00000f, -0.96593f
};

static const unsigned int corner_colors[] = {
    0xFF404040,
    0xFF404040,
    0xFF404040,
    0xFF404040,
    0xFF404040,
    0xFF404040,
    0xFF404040,
    0xFF404040,
    0xFF404040,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080
};

/* Road Damaged: 16 vertices, 24 triangles */
static const float damaged_verts[] = {
     -0.000000f,   0.000000f,   4.577094f,
      3.006575f,   0.000000f,   3.571108f,
     -0.000000f,   0.000000f,   6.000000f,
      6.000000f,   0.000000f,   6.000000f,
      6.000000f,   0.000000f,  -6.000000f,
      1.102746f,   0.000000f,  -2.118834f,
     -6.000000f,   0.000000f,  -6.000000f,
     -4.587196f,   0.000000f,  -0.215006f,
     -6.000000f,   0.000000f,   0.000000f,
     -4.515256f,   0.000000f,   0.000000f,
      1.102746f,   0.050000f,  -2.118834f,
      3.006575f,   0.050000f,   3.571108f,
     -4.587196f,   0.050000f,  -0.215006f,
     -2.683367f,   0.000000f,   5.474935f,
     -2.683367f,   0.050000f,   5.474935f,
     -6.000000f,   0.000000f,   6.000000f
};

static const int damaged_faces[] = {
    2, 1, 0,
    3, 1, 2,
    1, 3, 4,
    1, 4, 5,
    6, 5, 4,
    6, 7, 5,
    8, 7, 6,
    7, 8, 9,
    10, 1, 5,
    1, 10, 11,
    7, 10, 5,
    10, 7, 12,
    14, 9, 13,
    9, 14, 7,
    7, 14, 12,
    14, 1, 11,
    1, 14, 0,
    0, 14, 13,
    11, 12, 14,
    12, 11, 10,
    13, 2, 0,
    2, 13, 15,
    13, 8, 15,
    8, 13, 9
};

static const float damaged_normals[] = {
     0.00000f,  1.00000f,  0.00000f,
     0.00000f,  1.00000f,  0.00000f,
    -0.00000f,  1.00000f,  0.00000f,
     0.00000f,  1.00000f,  0.00000f,
     0.00000f,  1.00000f,  0.00000f,
     0.00000f,  1.00000f,  0.00000f,
     0.00000f,  1.00000f,  0.00000f,
     0.00000f,  1.00000f, -0.00000f,
     0.94832f,  0.00000f, -0.31730f,
     0.94832f,  0.00000f, -0.31730f,
    -0.31730f,  0.00000f, -0.94832f,
    -0.31730f,  0.00000f, -0.94832f,
    -0.94832f,  0.00000f,  0.31730f,
    -0.94832f,  0.00007f,  0.31730f,
    -0.94832f,  0.00000f,  0.31730f,
     0.31730f,  0.00000f,  0.94832f,
     0.31730f,  0.00002f,  0.94832f,
     0.31730f,  0.00000f,  0.94832f,
     0.00000f,  1.00000f,  0.00000f,
    -0.00000f,  1.00000f,  0.00000f,
    -0.00000f,  1.00000f,  0.00000f,
     0.00000f,  1.00000f,  0.00000f,
     0.00000f,  1.00000f,  0.00000f,
     0.00000f,  1.00000f,  0.00000f
};

static const unsigned int damaged_colors[] = {
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF404040,
    0xFF404040,
    0xFF404040,
    0xFF404040
};

/* Road Side: 10 vertices, 12 triangles */
static const float side_verts[] = {
      6.000000f,   0.000000f,   6.000000f,
     -0.000000f,   0.000000f,   6.000000f,
      6.000000f,   0.000000f,  -6.000000f,
     -0.000000f,   0.000000f,  -6.000000f,
     -0.000000f,   0.050000f,   6.000000f,
     -6.000000f,   0.050000f,   6.000000f,
     -0.000000f,   0.050000f,  -6.000000f,
     -6.000000f,   0.050000f,  -6.000000f,
     -6.000000f,   0.000000f,   6.000000f,
     -6.000000f,   0.000000f,  -6.000000f
};

static const int side_faces[] = {
    2, 1, 0,
    1, 2, 3,
    6, 5, 4,
    5, 6, 7,
    5, 1, 4,
    1, 5, 8,
    6, 1, 3,
    1, 6, 4,
    9, 6, 3,
    6, 9, 7,
    5, 9, 8,
    9, 5, 7
};

static const float side_normals[] = {
     0.00000f,  1.00000f, -0.00000f,
     0.00000f,  1.00000f,  0.00000f,
     0.00000f,  1.00000f, -0.00000f,
     0.00000f,  1.00000f,  0.00000f,
    -0.00000f,  0.00000f,  1.00000f,
     0.00000f,  0.00000f,  1.00000f,
     1.00000f,  0.00000f,  0.00000f,
     1.00000f, -0.00000f,  0.00000f,
     0.00000f,  0.00000f, -1.00000f,
    -0.00000f,  0.00000f, -1.00000f,
    -1.00000f, -0.00000f,  0.00000f,
    -1.00000f,  0.00000f,  0.00000f
};

static const unsigned int side_colors[] = {
    0xFF404040,
    0xFF404040,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080,
    0xFF808080
};

/* Pavement: 4 vertices, 2 triangles */
static const float pavement_verts[] = {
      6.000000f,   0.000000f,   6.000000f,
     -6.000000f,   0.000000f,   6.000000f,
      6.000000f,   0.000000f,  -6.000000f,
     -6.000000f,   0.000000f,  -6.000000f
};

static const int pavement_faces[] = {
    2, 1, 0,
    1, 2, 3
};

static const float pavement_normals[] = {
     0.00000f,  1.00000f, -0.00000f,
     0.00000f,  1.00000f,  0.00000f
};

static const unsigned int pavement_colors[] = {
    0xFF808080,
    0xFF808080
};

/* Grass: 4 vertices, 2 triangles */
static const float grass_verts[] = {
      6.000000f,   0.000000f,   6.000000f,
     -6.000000f,   0.000000f,   6.000000f,
      6.000000f,   0.000000f,  -6.000000f,
     -6.000000f,   0.000000f,  -6.000000f
};

static const int grass_faces[] = {
    2, 1, 0,
    1, 2, 3
};

static const float grass_normals[] = {
     0.00000f,  1.00000f, -0.00000f,
     0.00000f,  1.00000f,  0.00000f
};

static const unsigned int grass_colors[] = {
    0xFF228B22,
    0xFF228B22
};

/* Apply basic directional shading to a base color */
static uint32_t tile_shade_color(uint32_t base, float nx, float ny, float nz) {
    float dot = nx * 0.3f + ny * 0.7f + nz * 0.5f;
    if (dot < 0) dot = 0;
    float intensity = 0.4f + 0.6f * dot;
    if (intensity > 1.0f) intensity = 1.0f;

    uint32_t a = (base >> 24) & 0xFF;
    uint32_t r = (uint32_t)(((base >> 16) & 0xFF) * intensity);
    uint32_t g = (uint32_t)(((base >> 8) & 0xFF) * intensity);
    uint32_t b = (uint32_t)((base & 0xFF) * intensity);
    return (a << 24) | (r << 16) | (g << 8) | b;
}

/* Shared tile meshes */
static mesh_t *tile_meshes[TILE_COUNT];

static mesh_t *create_tile_mesh(const float *verts, const int *faces,
                                const float *normals, const unsigned int *colors,
                                int face_count) {
    mesh_t *mesh = (mesh_t *)malloc(sizeof(mesh_t));
    if (!mesh) return NULL;

    mesh->tri_count = face_count;
    mesh->triangles = (triangle_t *)malloc(sizeof(triangle_t) * face_count);
    if (!mesh->triangles) { free(mesh); return NULL; }
    memset(mesh->triangles, 0, sizeof(triangle_t) * face_count);
    mesh->base_color = 0xFF404040;

    for (int i = 0; i < face_count; i++) {
        int i0 = faces[i * 3 + 0];
        int i1 = faces[i * 3 + 1];
        int i2 = faces[i * 3 + 2];

        float nx = normals[i * 3 + 0];
        float ny = normals[i * 3 + 1];
        float nz = normals[i * 3 + 2];
        uint32_t shaded = tile_shade_color(colors[i], nx, ny, nz);

        mesh->triangles[i].v[0].pos.x = verts[i0 * 3 + 0];
        mesh->triangles[i].v[0].pos.y = verts[i0 * 3 + 1];
        mesh->triangles[i].v[0].pos.z = verts[i0 * 3 + 2];
        mesh->triangles[i].v[0].color = shaded;

        mesh->triangles[i].v[1].pos.x = verts[i1 * 3 + 0];
        mesh->triangles[i].v[1].pos.y = verts[i1 * 3 + 1];
        mesh->triangles[i].v[1].pos.z = verts[i1 * 3 + 2];
        mesh->triangles[i].v[1].color = shaded;

        mesh->triangles[i].v[2].pos.x = verts[i2 * 3 + 0];
        mesh->triangles[i].v[2].pos.y = verts[i2 * 3 + 1];
        mesh->triangles[i].v[2].pos.z = verts[i2 * 3 + 2];
        mesh->triangles[i].v[2].color = shaded;
    }

    return mesh;
}

void tile_init(void) {
    tile_meshes[TILE_STRAIGHT] = create_tile_mesh(straight_verts, straight_faces, straight_normals, straight_colors, 22);
    tile_meshes[TILE_CORNER] = create_tile_mesh(corner_verts, corner_faces, corner_normals, corner_colors, 50);
    tile_meshes[TILE_DAMAGED] = create_tile_mesh(damaged_verts, damaged_faces, damaged_normals, damaged_colors, 24);
    tile_meshes[TILE_SIDE] = create_tile_mesh(side_verts, side_faces, side_normals, side_colors, 12);
    tile_meshes[TILE_PAVEMENT] = create_tile_mesh(pavement_verts, pavement_faces, pavement_normals, pavement_colors, 2);
    tile_meshes[TILE_GRASS] = create_tile_mesh(grass_verts, grass_faces, grass_normals, grass_colors, 2);
}

void tile_shutdown(void) {
    for (int i = 0; i < TILE_COUNT; i++) {
        if (tile_meshes[i]) {
            mesh_destroy(tile_meshes[i]);
            tile_meshes[i] = NULL;
        }
    }
}

mesh_t *tile_get_mesh(tile_id_t id) {
    if (id < 0 || id >= TILE_COUNT) return tile_meshes[0];
    return tile_meshes[id];
}
